---
# This will config map will hold connection details that our sidecar will use to authenticate to Conjur
apiVersion: v1
kind: ConfigMap
metadata:
  name: conjur-connect-jwt
  namespace: conjur
  labels:
    app.kubernetes.io/name: "conjur-connect-configmap-jwt"
    app.kubernetes.io/instance: "conjur-jwt-configmap"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-connect-configmap-jwt"
data:
  CONJUR_ACCOUNT: demo
  CONJUR_APPLIANCE_URL: "https://<conjur-host>:8443"
  CONJUR_AUTHN_URL: "https://<conjur-host>:8443/authn-jwt/k8s-cluster1"
  CONJUR_AUTHENTICATOR_ID: "k8s-cluster1"
  CONJUR_VERSION: "5"
  CONJUR_SSL_CERTIFICATE: |- 
$CONJOR_PUBLIC_KEY
---
# Deployment for Conjur sidecar - push to file mode
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conjur-push-to-file
  name: demo-sidecar-push-to-file-jwt
  namespace: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-push-to-file
  template:
    metadata:
      labels:
        app: conjur-push-to-file
      annotations:
        # Sidecar configuration
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/conjur-secrets-policy-path.safe1: kubernetes/applications/safe/
        conjur.org/conjur-secrets.safe1: |
          - secret3: secret4
          - secret7: secret7
        conjur.org/secret-file-path.safe1: "./credentials.yaml"
        conjur.org/secret-file-format.safe1: "yaml"
        conjur.org/secrets-refresh-interval: 1m
        conjur.org/secrets-refresh-enabled: "true"
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Our demo application
      - name: demo-application
        image: centos:latest
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["infinity"]
        # Path to the file with the secrets 
        volumeMounts:
          - name: conjur-secrets
            mountPath: /opt/secrets/conjur
            readOnly: true
      # Sidecar
      - name: sidecar-push-to-file
        image: 'cyberark/secrets-provider-for-k8s:latest'
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: conjur-connect-jwt
        volumeMounts:
          - name: podinfo
            mountPath: /conjur/podinfo
          - name: conjur-secrets
            mountPath: /conjur/secrets
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        # This is where the sidecar keeps is authentiction token recieved from Conjur
        - name: conjur-secrets
          emptyDir:
            medium: Memory